# Generated by Django 6.0.5 on 2026-06-09 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, unique=True)),
                ('client_status', models.CharField(default='Active')),
            ],
            options={
                'ordering': ['client_name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('model_status', models.CharField(default='Active')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=100)),
                ('version_name', models.CharField(max_length=50)),
                ('batch_code', models.CharField(max_length=100)),
                ('client_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=100, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='warehouse.client')),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='warehouse.devicemodel')),
            ],
            options={
                'unique_together': {('model', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('device_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SCRAPPED', 'Scrapped'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.batch')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.devicemodel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.modelversion')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='model_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='warehouse.modelversion'),
        ),
    ]
