# Generated by Django 6.0.5 on 2026-06-14 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestaging',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='model_status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
