# Generated by Django 6.0 on 2026-05-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.CharField(default='Active'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='model_status',
            field=models.CharField(default='Active'),
        ),
    ]
