# Generated by Django 6.0.5 on 2026-06-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_client_client_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='model_name',
            field=models.CharField(max_length=100),
        ),
    ]
