# Generated by Django 6.0 on 2025-12-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.CharField(choices=[('HR', 'Human Resources'), ('FIN', 'Finance'), ('WAR', 'Warehouse'), ('REPC', 'Repairs Centre'), ('QC', 'Quality Control'), ('BER', 'Beyond Ergonomical Repair'), ('PROD_BA', 'BankA'), ('PROD_BB', 'BankB'), ('PROD_BC', 'BankC')], default='HR', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Staff', 'Staff'), ('Intern', 'Intern'), ('Fin_clerk', 'Finance Clerk'), ('HR_specialist', 'HR Specialist'), ('Warehouse_A', 'Warehouse Agent'), ('Repair_technician', 'Repair Technician'), ('QC_A', 'Quality Control Agent'), ('Prod_BA_A', 'Production BankA Agent'), ('Prod_BB_A', 'Production BankB Agent'), ('Prod_BC_A', 'Production BankC Agent')], default='Staff', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='not_set', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.department')),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.position')),
            ],
        ),
    ]
