# Generated by Django 6.0 on 2025-12-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('FIN', 'Finance'), ('WAR', 'Warehouse'), ('REPC', 'Repairs Centre'), ('QC', 'Quality Control'), ('BER', 'Beyond Ergonomical Repair'), ('PROD_BA', 'BankA'), ('PROD_BB', 'BankB'), ('PROD_BC', 'BankC')], default='HR', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Staff', 'Staff'), ('Intern', 'Intern'), ('Fin_clerk', 'Finance Clerk'), ('HR_specialist', 'HR Specialist'), ('Warehouse_A', 'Warehouse Agent'), ('Repair_technician', 'Repair Technician'), ('QC_A', 'Quality Control Agent'), ('Prod_BA_A', 'Production BankA Agent'), ('Prod_BB_A', 'Production BankB Agent'), ('Prod_BC_A', 'Production BankC Agent')], default='Staff', max_length=100),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
