# Generated by Django 6.0 on 2025-12-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_employee_department_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Staff', 'Staff'), ('Intern', 'Intern'), ('Fin_clerk', 'Finance Clerk'), ('HR_specialist', 'HR Specialist'), ('Warehouse_A', 'Warehouse Agent'), ('Repair_technician', 'Repair Technician'), ('QC_A', 'Quality Control Agent'), ('Prod_BA_A', 'Production BankA Agent'), ('Prod_BB_A', 'Production BankB Agent'), ('Prod_BC_A', 'Production BankC Agent')], default='Staff', max_length=100, verbose_name='Job Title'),
        ),
    ]
