# Generated by Django 6.0 on 2026-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Staff', 'Staff'), ('Intern', 'Intern'), ('Fin_clerk', 'Finance Clerk'), ('HR_specialist', 'HR Specialist'), ('Warehouse_A', 'Warehouse Agent'), ('Repair_technician', 'Repair Technician'), ('QC_A', 'Quality Control Agent'), ('Prod_BA_A', 'Production BankA Agent'), ('Prod_BB_A', 'Production BankB Agent'), ('Prod_BC_A', 'Production BankC Agent')], default='Staff', max_length=100),
        ),
    ]
